export const CountriesList = new Map([
  ['an', { nameRu: 'Андорра', nameEn: 'Andorra' }],
  ['an', { nameRu: 'Андорра', nameEn: 'Andorra' }],
  ['ae', { nameRu: 'ОАЭ', nameEn: 'United Arab Emirates' }],
  ['af', { nameRu: 'Афганистан', nameEn: 'Afghanistan' }],
  ['ac', { nameRu: 'Антигуа и Барбуда', nameEn: 'Antigua and Barbuda' }],
  ['av', { nameRu: 'Ангилья', nameEn: 'Anguilla' }],
  ['al', { nameRu: 'Албания', nameEn: 'Albania' }],
  ['am', { nameRu: 'Армения', nameEn: 'Armenia' }],
  ['ao', { nameRu: 'Ангола', nameEn: 'Angola' }],
  ['ar', { nameRu: 'Аргентина', nameEn: 'Argentina' }],
  ['aq', { nameRu: 'Американское Самоа', nameEn: 'American Samoa' }],
  ['au', { nameRu: 'Австрия', nameEn: 'Austria' }],
  ['as', { nameRu: 'Австралия', nameEn: 'Australia' }],
  ['aa', { nameRu: 'Аруба', nameEn: 'Aruba' }],
  ['aj', { nameRu: 'Азербайджан', nameEn: 'Azerbaijan' }],
  ['bk', { nameRu: 'Босния и Герцеговина', nameEn: 'Bosnia and Herzegovina' }],
  ['bb', { nameRu: 'Барбадос', nameEn: 'Barbados' }],
  ['bg', { nameRu: 'Бангладеш', nameEn: 'Bangladesh' }],
  ['be', { nameRu: 'Бельгия', nameEn: 'Belgium' }],
  ['uv', { nameRu: 'Буркина-Фасо', nameEn: 'Burkina Faso' }],
  ['bu', { nameRu: 'Болгария', nameEn: 'Bulgaria' }],
  ['ba', { nameRu: 'Бахрейн', nameEn: 'Bahrain' }],
  ['by', { nameRu: 'Бурунди', nameEn: 'Burundi' }],
  ['bn', { nameRu: 'Бенин', nameEn: 'Benin' }],
  ['tb', { nameRu: 'Сен-Бартелеми', nameEn: 'Saint Barthélemy' }],
  ['bd', { nameRu: 'Бермудские острова', nameEn: 'Bermuda' }],
  ['bx', { nameRu: 'Бруней', nameEn: 'Brunei' }],
  ['bl', { nameRu: 'Боливия', nameEn: 'Bolivia' }],
  ['br', { nameRu: 'Бразилия', nameEn: 'Brazil' }],
  ['bf', { nameRu: 'Багамские острова', nameEn: 'Bahamas' }],
  ['bt', { nameRu: 'Бутан', nameEn: 'Bhutan' }],
  ['bv', { nameRu: 'Остров Буве', nameEn: 'Bouvet Island' }],
  ['bc', { nameRu: 'Ботсвана', nameEn: 'Botswana' }],
  ['bo', { nameRu: 'Беларусь', nameEn: 'Belarus' }],
  ['bh', { nameRu: 'Белиз', nameEn: 'Belize' }],
  ['ca', { nameRu: 'Канада', nameEn: 'Canada' }],
  [
    'ck',
    { nameRu: 'Кокосовые (Килинг) острова', nameEn: 'Cocos (Keeling) Islands' },
  ],
  ['cg', { nameRu: 'ДР Конго', nameEn: 'DR Congo' }],
  [
    'ct',
    {
      nameRu: 'Центральноафриканская Республика',
      nameEn: 'Central African Republic',
    },
  ],
  ['cf', { nameRu: 'Республика Конго', nameEn: 'Congo Republic' }],
  ['sz', { nameRu: 'Швейцария', nameEn: 'Switzerland' }],
  ['iv', { nameRu: 'Берег Слоновой Кости', nameEn: 'Ivory Coast' }],
  ['cw', { nameRu: 'Острова Кука', nameEn: 'Cook Islands' }],
  ['ci', { nameRu: 'Чили', nameEn: 'Chile' }],
  ['cm', { nameRu: 'Камерун', nameEn: 'Cameroon' }],
  ['ch', { nameRu: 'Китай', nameEn: 'China' }],
  ['co', { nameRu: 'Колумбия', nameEn: 'Colombia' }],
  ['cs', { nameRu: 'Коста-Рика', nameEn: 'Costa Rica' }],
  ['cu', { nameRu: 'Куба', nameEn: 'Cuba' }],
  ['cv', { nameRu: 'Кабо-Верде', nameEn: 'Cabo Verde' }],
  ['uc', { nameRu: 'Кюрасао', nameEn: 'Curaçao' }],
  ['kt', { nameRu: 'Остров Рождества', nameEn: 'Christmas Island' }],
  ['cy', { nameRu: 'Кипр', nameEn: 'Cyprus' }],
  ['ez', { nameRu: 'Чехия', nameEn: 'Czechia' }],
  ['gm', { nameRu: 'Германия', nameEn: 'Germany' }],
  ['dj', { nameRu: 'Джибути', nameEn: 'Djibouti' }],
  ['da', { nameRu: 'Дания', nameEn: 'Denmark' }],
  ['do', { nameRu: 'Доминика', nameEn: 'Dominica' }],
  ['dr', { nameRu: 'Доминиканская Республика', nameEn: 'Dominican Republic' }],
  ['ag', { nameRu: 'Алжир', nameEn: 'Algeria' }],
  ['ec', { nameRu: 'Эквадор', nameEn: 'Ecuador' }],
  ['en', { nameRu: 'Эстония', nameEn: 'Estonia' }],
  ['eg', { nameRu: 'Египет', nameEn: 'Egypt' }],
  ['wi', { nameRu: 'Западная Сахара', nameEn: 'Western Sahara' }],
  ['er', { nameRu: 'Эритрея', nameEn: 'Eritrea' }],
  ['sp', { nameRu: 'Испания', nameEn: 'Spain' }],
  ['et', { nameRu: 'Эфиопия', nameEn: 'Ethiopia' }],
  ['fi', { nameRu: 'Финляндия', nameEn: 'Finland' }],
  ['fj', { nameRu: 'Фиджи', nameEn: 'Fiji' }],
  ['fk', { nameRu: 'Фолклендские острова', nameEn: 'Falkland Islands' }],
  ['fm', { nameRu: 'Микронезия', nameEn: 'Micronesia' }],
  ['fo', { nameRu: 'Фарерские острова', nameEn: 'Faroe Islands' }],
  ['fr', { nameRu: 'Франция', nameEn: 'France' }],
  ['gb', { nameRu: 'Габон', nameEn: 'Gabon' }],
  ['uk', { nameRu: 'Великобритания', nameEn: 'United Kingdom' }],
  ['gj', { nameRu: 'Гренада', nameEn: 'Grenada' }],
  ['gg', { nameRu: 'Грузия', nameEn: 'Georgia' }],
  ['fg', { nameRu: 'Французская Гвиана', nameEn: 'French Guiana' }],
  ['gk', { nameRu: 'Гернси', nameEn: 'Guernsey' }],
  ['gh', { nameRu: 'Гана', nameEn: 'Ghana' }],
  ['gi', { nameRu: 'Гибралтар', nameEn: 'Gibraltar' }],
  ['gl', { nameRu: 'Гренландия', nameEn: 'Greenland' }],
  ['ga', { nameRu: 'Гамбия', nameEn: 'The Gambia' }],
  ['gv', { nameRu: 'Гвинея', nameEn: 'Guinea' }],
  ['gp', { nameRu: 'Гваделупа', nameEn: 'Guadeloupe' }],
  ['ek', { nameRu: 'Экваториальная Гвинея', nameEn: 'Equatorial Guinea' }],
  ['gr', { nameRu: 'Греция', nameEn: 'Greece' }],
  [
    'sx',
    {
      nameRu: 'Южная Георгия и Южные Сандвичевы острова',
      nameEn: 'South Georgia and South Sandwich Islands',
    },
  ],
  ['gt', { nameRu: 'Гватемала', nameEn: 'Guatemala' }],
  ['gq', { nameRu: 'Гуам', nameEn: 'Guam' }],
  ['pu', { nameRu: 'Гвинея-Бисау', nameEn: 'Guinea-Bissau' }],
  ['gy', { nameRu: 'Гайана', nameEn: 'Guyana' }],
  ['hk', { nameRu: 'Гонконг', nameEn: 'Hong Kong' }],
  [
    'hm',
    {
      nameRu: 'Острова Херд и Макдональд',
      nameEn: 'Heard and McDonald Islands',
    },
  ],
  ['ho', { nameRu: 'Гондурас', nameEn: 'Honduras' }],
  ['hr', { nameRu: 'Хорватия', nameEn: 'Croatia' }],
  ['ha', { nameRu: 'Гаити', nameEn: 'Haiti' }],
  ['hu', { nameRu: 'Венгрия', nameEn: 'Hungary' }],
  ['id', { nameRu: 'Индонезия', nameEn: 'Indonesia' }],
  ['ei', { nameRu: 'Ирландия', nameEn: 'Ireland' }],
  ['is', { nameRu: 'Израиль', nameEn: 'Israel' }],
  ['im', { nameRu: 'Остров Мэн', nameEn: 'Isle of Man' }],
  ['in', { nameRu: 'Индия', nameEn: 'India' }],
  [
    'io',
    {
      nameRu: 'Британская территория в Индийском океане',
      nameEn: 'British Indian Ocean Territory',
    },
  ],
  ['iz', { nameRu: 'Ирак', nameEn: 'Iraq' }],
  ['ir', { nameRu: 'Иран', nameEn: 'Iran' }],
  ['ic', { nameRu: 'Исландия', nameEn: 'Iceland' }],
  ['it', { nameRu: 'Италия', nameEn: 'Italy' }],
  ['je', { nameRu: 'Джерси', nameEn: 'Jersey' }],
  ['jm', { nameRu: 'Ямайка', nameEn: 'Jamaica' }],
  ['jo', { nameRu: 'Иордания', nameEn: 'Jordan' }],
  ['ja', { nameRu: 'Япония', nameEn: 'Japan' }],
  ['ke', { nameRu: 'Кения', nameEn: 'Kenya' }],
  ['kg', { nameRu: 'Кыргызстан', nameEn: 'Kyrgyzstan' }],
  ['cb', { nameRu: 'Камбоджа', nameEn: 'Cambodia' }],
  ['kr', { nameRu: 'Кирибати', nameEn: 'Kiribati' }],
  ['cn', { nameRu: 'Коморские острова', nameEn: 'Comoros' }],
  ['sc', { nameRu: 'Сент-Китс и Невис', nameEn: 'St Kitts and Nevis' }],
  ['kn', { nameRu: 'Северная Корея', nameEn: 'North Korea' }],
  ['ks', { nameRu: 'Южная Корея', nameEn: 'South Korea' }],
  ['ku', { nameRu: 'Кувейт', nameEn: 'Kuwait' }],
  ['cj', { nameRu: 'Каймановы острова', nameEn: 'Cayman Islands' }],
  ['kz', { nameRu: 'Казахстан', nameEn: 'Kazakhstan' }],
  ['la', { nameRu: 'Лаос', nameEn: 'Laos' }],
  ['le', { nameRu: 'Ливан', nameEn: 'Lebanon' }],
  ['st', { nameRu: 'Сент-Люсия', nameEn: 'Saint Lucia' }],
  ['ls', { nameRu: 'Лихтенштейн', nameEn: 'Liechtenstein' }],
  ['ce', { nameRu: 'Шри-Ланка', nameEn: 'Sri Lanka' }],
  ['li', { nameRu: 'Либерия', nameEn: 'Liberia' }],
  ['lt', { nameRu: 'Лесото', nameEn: 'Lesotho' }],
  ['lh', { nameRu: 'Литва', nameEn: 'Lithuania' }],
  ['lu', { nameRu: 'Люксембург', nameEn: 'Luxembourg' }],
  ['lg', { nameRu: 'Латвия', nameEn: 'Latvia' }],
  ['ly', { nameRu: 'Ливия', nameEn: 'Libya' }],
  ['mo', { nameRu: 'Марокко', nameEn: 'Morocco' }],
  ['mn', { nameRu: 'Монако', nameEn: 'Monaco' }],
  ['md', { nameRu: 'Молдова', nameEn: 'Moldova' }],
  ['mj', { nameRu: 'Черногория', nameEn: 'Montenegro' }],
  ['rn', { nameRu: 'Сент-Мартин', nameEn: 'Saint Martin' }],
  ['ma', { nameRu: 'Мадагаскар', nameEn: 'Madagascar' }],
  ['rm', { nameRu: 'Маршалловы острова', nameEn: 'Marshall Islands' }],
  ['mk', { nameRu: 'Северная Македония', nameEn: 'North Macedonia' }],
  ['ml', { nameRu: 'Мали', nameEn: 'Mali' }],
  ['bm', { nameRu: 'Мьянма', nameEn: 'Myanmar' }],
  ['mg', { nameRu: 'Монголия', nameEn: 'Mongolia' }],
  ['mc', { nameRu: 'Макао', nameEn: 'Macao' }],
  [
    'cq',
    {
      nameRu: 'Северные Марианские острова',
      nameEn: 'Northern Mariana Islands',
    },
  ],
  ['mb', { nameRu: 'Мартиника', nameEn: 'Martinique' }],
  ['mr', { nameRu: 'Мавритания', nameEn: 'Mauritania' }],
  ['mh', { nameRu: 'Монтсеррат', nameEn: 'Montserrat' }],
  ['mt', { nameRu: 'Мальта', nameEn: 'Malta' }],
  ['mp', { nameRu: 'Маврикий', nameEn: 'Mauritius' }],
  ['mv', { nameRu: 'Мальдивы', nameEn: 'Maldives' }],
  ['mi', { nameRu: 'Малави', nameEn: 'Malawi' }],
  ['mx', { nameRu: 'Мексика', nameEn: 'Mexico' }],
  ['my', { nameRu: 'Малайзия', nameEn: 'Malaysia' }],
  ['mz', { nameRu: 'Мозамбик', nameEn: 'Mozambique' }],
  ['wa', { nameRu: 'Намибия', nameEn: 'Namibia' }],
  ['nc', { nameRu: 'Новая Каледония', nameEn: 'New Caledonia' }],
  ['ng', { nameRu: 'Нигер', nameEn: 'Niger' }],
  ['nf', { nameRu: 'Остров Норфолк', nameEn: 'Norfolk Island' }],
  ['ni', { nameRu: 'Нигерия', nameEn: 'Nigeria' }],
  ['nu', { nameRu: 'Никарагуа', nameEn: 'Nicaragua' }],
  ['nl', { nameRu: 'Нидерланды', nameEn: 'Netherlands' }],
  ['no', { nameRu: 'Норвегия', nameEn: 'Norway' }],
  ['np', { nameRu: 'Непал', nameEn: 'Nepal' }],
  ['nr', { nameRu: 'Науру', nameEn: 'Nauru' }],
  ['ne', { nameRu: 'Ниуэ', nameEn: 'Niue' }],
  ['nz', { nameRu: 'Новая Зеландия', nameEn: 'New Zealand' }],
  ['mu', { nameRu: 'Оман', nameEn: 'Oman' }],
  ['pm', { nameRu: 'Панама', nameEn: 'Panama' }],
  ['pe', { nameRu: 'Перу', nameEn: 'Peru' }],
  ['fp', { nameRu: 'Французская Полинезия', nameEn: 'French Polynesia' }],
  ['pp', { nameRu: 'Папуа-Новая Гвинея', nameEn: 'Papua New Guinea' }],
  ['rp', { nameRu: 'Филиппины', nameEn: 'Philippines' }],
  ['pk', { nameRu: 'Пакистан', nameEn: 'Pakistan' }],
  ['pl', { nameRu: 'Польша', nameEn: 'Poland' }],
  ['sb', { nameRu: 'Сен-Пьер и Микелон', nameEn: 'Saint Pierre and Miquelon' }],
  ['pc', { nameRu: 'Острова Питкэрн', nameEn: 'Pitcairn Islands' }],
  ['rq', { nameRu: 'Пуэрто-Рико', nameEn: 'Puerto Rico' }],
  ['we', { nameRu: 'Палестина', nameEn: 'Palestine' }],
  ['po', { nameRu: 'Португалия', nameEn: 'Portugal' }],
  ['ps', { nameRu: 'Палау', nameEn: 'Palau' }],
  ['pa', { nameRu: 'Парагвай', nameEn: 'Paraguay' }],
  ['qa', { nameRu: 'Катар', nameEn: 'Qatar' }],
  ['re', { nameRu: 'Реюньон', nameEn: 'Réunion' }],
  ['ro', { nameRu: 'Румыния', nameEn: 'Romania' }],
  ['ri', { nameRu: 'Сербия', nameEn: 'Serbia' }],
  ['rs', { nameRu: 'Россия', nameEn: 'Russia' }],
  ['rw', { nameRu: 'Руанда', nameEn: 'Rwanda' }],
  ['sa', { nameRu: 'Саудовская Аравия', nameEn: 'Saudi Arabia' }],
  ['bp', { nameRu: 'Соломоновы острова', nameEn: 'Solomon Islands' }],
  ['se', { nameRu: 'Сейшельские острова', nameEn: 'Seychelles' }],
  ['su', { nameRu: 'СССР', nameEn: 'USSR' }],
  ['sw', { nameRu: 'Швеция', nameEn: 'Sweden' }],
  ['sn', { nameRu: 'Сингапур', nameEn: 'Singapore' }],
  ['sh', { nameRu: 'Остров Святой Елены', nameEn: 'Saint Helena' }],
  ['si', { nameRu: 'Словения', nameEn: 'Slovenia' }],
  ['sv', { nameRu: 'Шпицберген и Ян-Майен', nameEn: 'Svalbard and Jan Mayen' }],
  ['lo', { nameRu: 'Словакия', nameEn: 'Slovakia' }],
  ['sl', { nameRu: 'Сьерра-Леоне', nameEn: 'Sierra Leone' }],
  ['sm', { nameRu: 'Сан-Марино', nameEn: 'San Marino' }],
  ['sg', { nameRu: 'Сенегал', nameEn: 'Senegal' }],
  ['so', { nameRu: 'Сомали', nameEn: 'Somalia' }],
  ['ns', { nameRu: 'Суринам', nameEn: 'Suriname' }],
  ['od', { nameRu: 'Южный Судан', nameEn: 'South Sudan' }],
  ['tp', { nameRu: 'Сан-Томе и Принсипи', nameEn: 'São Tomé and Príncipe' }],
  ['es', { nameRu: 'Сальвадор', nameEn: 'El Salvador' }],
  ['nn', { nameRu: 'Синт-Мартен', nameEn: 'Sint Maarten' }],
  ['sy', { nameRu: 'Сирия', nameEn: 'Syria' }],
  ['wz', { nameRu: 'Эсватини', nameEn: 'Eswatini' }],
  [
    'tk',
    { nameRu: 'Острова Теркс и Кайкос', nameEn: 'Turks and Caicos Islands' },
  ],
  ['cd', { nameRu: 'Чад', nameEn: 'Chad' }],
  [
    'fs',
    {
      nameRu: 'Французские южные территории',
      nameEn: 'French Southern Territories',
    },
  ],
  ['to', { nameRu: 'Того', nameEn: 'Togo' }],
  ['th', { nameRu: 'Таиланд', nameEn: 'Thailand' }],
  ['ti', { nameRu: 'Таджикистан', nameEn: 'Tajikistan' }],
  ['tl', { nameRu: 'Токелау', nameEn: 'Tokelau' }],
  ['tt', { nameRu: 'Тимор-Лешти', nameEn: 'Timor-Leste' }],
  ['tx', { nameRu: 'Туркменистан', nameEn: 'Turkmenistan' }],
  ['ts', { nameRu: 'Тунис', nameEn: 'Tunisia' }],
  ['tn', { nameRu: 'Тонга', nameEn: 'Tonga' }],
  ['tu', { nameRu: 'Турция', nameEn: 'Turkey' }],
  ['td', { nameRu: 'Тринидад и Тобаго', nameEn: 'Trinidad and Tobago' }],
  ['tv', { nameRu: 'Тувалу', nameEn: 'Tuvalu' }],
  ['tw', { nameRu: 'Тайвань', nameEn: 'Taiwan' }],
  ['tz', { nameRu: 'Танзания', nameEn: 'Tanzania' }],
  ['up', { nameRu: 'Украина', nameEn: 'Ukraine' }],
  ['ug', { nameRu: 'Уганда', nameEn: 'Uganda' }],
  ['us', { nameRu: 'Соединенные Штаты', nameEn: 'United States' }],
  ['uy', { nameRu: 'Уругвай', nameEn: 'Uruguay' }],
  ['uz', { nameRu: 'Узбекистан', nameEn: 'Uzbekistan' }],
  ['vt', { nameRu: 'Ватикан', nameEn: 'Vatican City' }],
  [
    'vc',
    { nameRu: 'Сент-Винсент и Гренадины', nameEn: 'St Vincent and Grenadines' },
  ],
  ['ve', { nameRu: 'Венесуэла', nameEn: 'Venezuela' }],
  [
    'vi',
    {
      nameRu: 'Британские Виргинские острова',
      nameEn: 'British Virgin Islands',
    },
  ],
  ['vq', { nameRu: 'Виргинские острова США', nameEn: 'U.S. Virgin Islands' }],
  ['vm', { nameRu: 'Вьетнам', nameEn: 'Vietnam' }],
  ['nh', { nameRu: 'Вануату', nameEn: 'Vanuatu' }],
  ['wf', { nameRu: 'Уоллис и Футуна', nameEn: 'Wallis and Futuna' }],
  ['ws', { nameRu: 'Самоа', nameEn: 'Samoa' }],
  ['kv', { nameRu: 'Косово', nameEn: 'Kosovo' }],
  ['ym', { nameRu: 'Йемен', nameEn: 'Yemen' }],
  ['mf', { nameRu: 'Майотта', nameEn: 'Mayotte' }],
  ['sf', { nameRu: 'Южная Африка', nameEn: 'South Africa' }],
  ['za', { nameRu: 'Замбия', nameEn: 'Zambia' }],
  ['zi', { nameRu: 'Зимбабве', nameEn: 'Zimbabwe' }],
]);
