export class MovieDto {
  readonly authorId: number;
  readonly string: string;
  readonly essenceTable: string;
  readonly essenceId: number;
  "videos.trailers": {  }[];
  videosTeasers: string[];
  status: string;
  externalIdKpHD: string;
  externalIdImdb: string;
  externalIdTmdb: number;
  ratingKp: number;
  ratingImdb: number;
  ratingFilmCritics: number;
  ratingRussianFilmCritics: number;
  ratingAwait: number;
  votesKp: number;
  votesImdb: number;
  votesFilmCritics: number;
  votesRussianFilmCritics: number;
  votesAwait: number;
  backdropUrl: string;
  backdropPreviewUrl: string;
  movieLength: number;
  productionCompanies: string[];
  id: number;
  type: string;
  name: string;
  description: string;
  premiereCountry: string;
  premiereWorld: string;
  slogan: string;
  year: number;
  posterUrl: string;
  posterPreviewUrl: string;
  facts: string[];
  genres: string[];
  countries: string[];
  seasonsInfo: string[];
  persons: string[];
  typeNumber: number;
  alternativeName: string;
  enName: string;
  names: string[];
  ratingMpaa: string;
  shortDescription: string;
  similarMovies: string[];
  sequelsAndPrequels: string[];
  ageRating: string;
  logoUrl: string;
  watchabilityItems: string;
  top10: string;
  top250: string;
}
